#GET ALL COURSE
GET http://localhost:5000/api/admin/courses

###
#ADD A COURSE
POST http://localhost:5000/api/admin/courses
Content-Type: application/json

{
    "title":"Web Dev",
    "author":"Brad Traversy",
    "description": "lorem ipsum dolor amet"
}

###
#GET ONE COURSE
GET http://localhost:5000/api/admin/courses/5f5f7819884c272620ca5a09

###
#UPDATE A COURSE
PUT http://localhost:5000/api/admin/courses/5f5f7819884c272620ca5a09
Content-Type: application/json

{
    "title":"Advanced Web Dev Bootcamp",
    "author":"Colt Steele",
    "description": "lorem ipsum dolor amet"
}

###
#DELETE A COURSE
DELETE http://localhost:5000/api/admin/courses/5f5f7819884c272620ca5a09