POST http://localhost:5000/api/register
Content-Type: application/json

{
    "name":"Pranjal Chourasia",
    "email":"abc@xyz.com",
    "password":"Mamba@4399"
}

###
POST http://localhost:5000/api/login
Content-Type: application/json

{
    "email":"abc@xyz.com",
    "password":"Mamba@4399"
}

###
POST http://localhost:5000/api/user
Content-Type: application/json
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlzQWRtaW4iOmZhbHNlLCJpc3ZlcmlmaWVkIjpmYWxzZSwiZW5yb2xsZWRfY291cnNlc19pZCI6W10sIl9pZCI6IjVmNWY5YTBjZmVjNmM4MjU1ODNmMGZlYyIsIm5hbWUiOiJQcmFuamFsIENob3VyYXNpYSIsImVucm9sbGVkX2NvdXJzZXMiOltdfSwiaWF0IjoxNjAwMTAxNDQyLCJleHAiOjE2MDAxMDUwNDJ9.eZrdd0fdmrUG-8pRKT67Av8Sm7uygEi3V09SRIU93qk